name: app_ui
description: UI Toolkit for the App Flutter Application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: 3.13.8

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  intl: ^0.18.1
  mockingjay: ^0.4.0
  mocktail_image_network: ^1.0.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  lineLength: 80

  integrations:
    flutter_svg: true
